package com.github.servb.pph.pheroes.Game

val creditsText = listOf(
    "#FFB0SerVB #FFFFproudly presents",
    "",
    "#FFFFa port (#F0BFhttps://github.com/SerVB/pph#FFFF)",
    "",
    "#FFFFof legendary",
    "",
    "#FFB0#S2Pocket Heroes",
    "#FDDDv.1.04 beta",
    "#FDDDby iO UPG",
    "",
    "",
    "#FFB0Programmers:",
    "#FDDDRobert Tarasov",
    "#FDDD(Tutankhamen/iO)",
    "#FDDDAnton Stuk",
    "#FDDDSiGMan/iO",
    "#FDDDAndrey Kiryushkin (Hedin)",
    "",
    "#FFB0Artists:",
    "#FDDDEugene Ivanov (Jim)",
    "#FDDDDmitry Zaitsev",
    "#FDDDAlek Revyako",
    "#FDDDMihail Chilikin",
    "#FDDDOleg Kirshev",
    "#FDDDVladimir Gulevskiy (GRAFuS)",
    "#FDDDKevin Brock (tekpir8)",
    "#FDDDStanislav (Mr.Flasher)",
    "#FDDDAlexey Garkushin (GAS13)",
    "#FDDDTutankhamen/iO",
    "",
    "#FFB0Guest artists:",
    "#FDDDSimon Butler",
    "#FDDDDanny Flexner",
    "#FDDDIan Schlaepfer",
    "#FDDDPaul Noble",
    "#FDDDMichael Elwin Setiadi",
    "#FDDDDmitry Koshelev",
    "#FDDDIvan Ivanov",
    "",
    "#FFB0Map designers:",
    "#FDDDRoman Tersky (Mongol)",
    "#FDDDKevin Brock (tekpir8)",
    "#FDDDRuslan Pantyushin (Lain)",
    "#FDDDTsukanov Nikita (keks-n)",
    "#FDDDEugene Ivanov (Jim)",
    "#FDDDYaroslaw Artemiev (Yaros)",
    "#FDDDVictor Chirea (victorash)",
    "#FDDDObi-Van (Stas)",
    "#FDDDArtem Stragnik (Starmi)",
    "#FDDDMihail Loktionov (Matador)",
    "#FDDDDraco Lockhard",
    "#FDDDTutankhamen/iO",
    "",
    "#FFB0WEB master:",
    "#FDDDSergey Indiukov (DukereD)",
    "#FDDDTimur Parfentsev (Basmach)",
    "",
    "#FFB0Manual and Help file:",
    "#FDDDAndy Young (67L48)",
    "#FDDDVictor Chirea (victorash)",
    "#FDDDSergey Indiukov",
    "",
    "#FFB0Testers:",
    "#FDDDYaroslaw Artemiev (Yaros)",
    "#FDDDStanislav (Mr.Flasher)",
    "#FDDDAndrew Busygin",
    "#FDDDSergey Indiukov (DukereD)",
    "#FDDDVictor Chirea (victorash)",
    "#FDDDEugene Ivanov (Jim)",
    "#FDDDObi-Van (Stas)",
    "#FDDDIvan Alekhin (gsvano)",
    "#FDDDBaRaKuDa (Alexander)",
    "#FDDDArtem Stragnik (Starmi)",
    "#FDDDChibis",
    "#FDDDMihail Loktionov (Matador)",
    "#FDDDAlexey Muratov (Till)",
    "#FDDDAlexander Muranov (SAS)",
    "#FDDDTsukanov Nikita (keks-n)",
    "",
    "#FFB0Alpha version supporters:",
    "#FDDDAndrey Glinsky",
    "#FDDDFjodor Dzjuba",
    "#FDDDJustin Jones",
    "#FDDDChibis",
    "#FDDDRalph Sanders",
    "#FDDDChris Bygrave",
    "#FDDDDavid Zuravel",
    "#FDDDArtem Stragnik (Starmi)",
    "#FDDDValdemar",
    "#FDDDRS",
    "#FDDDSergey Indiukov (DukereD)",
    "#FDDDTom Fitzpatrick",
    "#FDDDRoman Klyachkivsky",
    "#FDDDOlivier Binda",
    "#FDDDEmanuel Mayer",
    "#FDDDKonstantin Ilyin",
    "#FDDDPaul Cook",
    "#FDDDAnton Rozen",
    "#FDDDPetr Cermak",
    "#FDDDNorry Messina",
    "#FDDDCary Fleming",
    "#FDDDLjusalfheim (4PDA)",
    "#FDDDMarc Ruder",
    "#FDDDMichael Thomas",
    "#FDDDJean-Paul Lacombe",
    "#FDDDestena.ru",
    "#FDDDMaksim Frolov",
    "#FDDDMiroslav Dvoracek",
    "#FDDDEvgeny Kremer",
    "#FDDDGrulezZ",
    "#FDDDLSDsl",
    "#FDDDSergey Chalykh",
    "#FDDDAnton Stuk",
    "#FDDDDmitry Sinchilin",
    "#FDDDAleksander Larionov",
    "",
    "#FFB0Special thanx to:",
    "#FDDDJon Van Caneghem",
    "#FDDDDmitry Lekhno (Krondor)",
)