package com.github.servb.pph.pheroes.common

/*
 * TODO: Use an external file.
 * This file is automatically generated by Pocket Heroes resource compiler.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

const val CSND_PREBATTLE = 0
const val CSND_QUEST_DLG = 1
const val CSND_NEW_LEVEL_DLG = 2
const val CSND_TREASURE = 3
const val CSND_FLAG_MINE = 4
const val CSND_BUTTON = 5
const val CSND_DIG = 6
const val CSND_SEAWASH = 7
const val CSND_PICKUP01 = 8
const val CSND_PICKUP02 = 9
const val CSND_PICKUP03 = 10
const val CSND_PICKUP04 = 11
const val CSND_PICKUP05 = 12
const val CSND_DEL_GUARD = 13
const val CSND_TELEPORT_OUT = 14
const val CSND_HMOVE01 = 15
const val CSND_HMOVE02 = 16
const val CSND_HMOVE03 = 17
const val CSND_HMOVE04 = 18
const val CSND_HMOVE05 = 19
const val CSND_HMOVE06 = 20
const val CSND_ALCH_LAB = 21
const val CSND_SAWMILL = 22
const val CSND_MINE = 23
const val CSND_SHRINE = 24
const val CSND_STABLES = 25
const val CSND_VOLCANO = 26
const val CSND_LAKES = 27
const val CSND_TELEPORT = 28
const val CSND_ARENA = 29
const val CSND_BLACKSMITH = 30
const val CSND_HYDRA_POND = 31
const val CSND_MARKETPLACE = 32
const val CSND_ARCHERS_HUT = 33
const val CSND_HAUNTED_HOUSE = 34
